trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build Maven Project'
  steps:
  - script: |
      sudo apt-get install -y maven
    displayName: 'Install Maven'

  - script: 'mvn clean install'
    displayName: 'Maven Build' 


- job: MendScan
  displayName: 'Mend Unified Agent Scan'
  steps:
  - script: |
      sudo apt-get install -y maven

      # Download Unified Agent
      curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
      echo Unified Agent downloaded successfully

      # Run Unified Agent
      java -jar wss-unified-agent.jar
    displayName: 'Download and Run Unified Agent'
    env:
      WS_APIKEY: $(APIKEY)
      WS_USERKEY: $(USERKEY)
      WS_WSS_URL: $(WSS_URL)
      WS_PRODUCTNAME: AZDO_$(WebGoatAzure)
      WS_PROJECTNAME: $(WebGoat)

