trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: InstallMaven
  displayName: 'Install and Check Maven'
  steps:
  - script: |
      # Install Maven
      sudo apt-get install -y maven

      # Check Maven version
      mvn -version
    displayName: 'Install and Check Maven'

- job: MendScan
  displayName: 'Mend Unified Agent Scan'
  dependsOn: InstallMaven
  steps:
  - script: |
      # Download Unified Agent
      curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
      echo Unified Agent downloaded successfully

      # Run Unified Agent with Maven integration and WS_maven environment variables
      java -jar wss-unified-agent.jar -d . -r
    displayName: 'Run Unified Agent Scan'
    env:
      WS_APIKEY: $(APIKEY)
      WS_USERKEY: $(USERKEY)
      WS_WSS_URL: https://saas.mend.io/agent
      WS_PRODUCTNAME: AZDO_$(System.TeamProject)
      WS_PROJECTNAME: $(Build.Repository.Name)_$(Build.SourceBranchName)
      WS_FILESYSTEMSCAN: false
      WS_MAVEN.RESOLVEDEPENDENCIES: TRUE
      WS_RUNPRESTEP: TRUE


