trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: InstallMaven
  displayName: 'Install and Check Maven'
  steps:
  - script: |
      # Install Maven
      sudo apt-get install -y maven

      # Check Maven version
      mvn -version
    displayName: 'Install and Check Maven'

- job: MendScan
  displayName: 'Mend Unified Agent Scan'
  steps:
  - task: WhiteSource@21
    inputs:
      cwd: '$(System.DefaultWorkingDirectory)'
      projectName: 'TestingTaskProjectName'

    displayName: 'Run Unified Agent Scan'

    env:
      WS_APIKEY: $(APIKEY)
      WS_USERKEY: $(USERKEY)
      WS_WSS_URL: $(WSS_URL)
      WS_PRODUCTNAME: AZDO_$(WebGoatAzure)
      WS_PROJECTNAME: $(WebGoat)
      WS_FILESYSTEMSCAN: false
      WS_MAVEN.RESOLVEDEPENDENCIES: TRUE
      WS_RUNPRESTEP: TRUE


