trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: InstallMaven
  displayName: 'Install and Check Maven'
  steps:
  - script: |
      # Install Maven
      sudo apt-get install -y maven

      # Check Maven version
      mvn -version
    displayName: 'Install and Check Maven'

  - script: |
      curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
      echo Unified Agent downloaded successfully
      java -jar wss-unified-agent.jar


    env:
      WS_APIKEY: $(APIKEY)
      WS_WSS_URL: $(WSS_URL)
      WS_PRODUCTNAME: AZDO_$(System.TeamProject)
      WS_PROJECTNAME: $(Build.Repository.Name)_$(Build.SourceBranchName)
      WS_UPDATEINVENTORY: true
      WS_FORCEUPDATE: true
      WS_FORCEUPDATE_FAILBUILDONPOLICYCHECK: true
      WS_CHECKPOLICIES: true
    displayName: 'Mend Unified Agent Scan'

